# Transformer config,


[general]
  device = "cpu"
  text   = "hello, how is your day going!"
  input_text  = "hello, how is your day going!"
  output_text = ""

[epoch]
  epoch_total = 32
  epoch_train = 1
  epoch_eval  = 1
  epoch_infer = 1

[vocab]
  unk_token = "[UNK]"
  pad_token = "[PAD]"
  sos_token = "[SOS]"
  eos_token = "[EOS]"
  unk_id = 0
  pad_id = 0
  sos_id = 0
  eos_id = 0

[dataset]
  batch_size    = 8
  max_seq_len   = 128
  shuffle_train = true
  shuffle_eval  = false
  tokenizer_src    = {}
  tokenizer_tgt    = {}
  id2word_src      = {}
  id2word_tgt      = {}
  databatchs_train = []
  databatchs_eval  = []


